name: result_monad
description: A Dart implementation of the Result Monad which allows for more expressive result generation and processing without using exceptions.
version: 2.5.0
homepage: https://github.com/NEONSCREENS/flutter-result-monad

environment:
  sdk: '>=2.14.4 <4.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.4
