name: result_monad
description: A Dart implementation of the Result Monad which allows for more expressive result generation and processing without using exceptions.
version: 2.1.0
homepage: https://gitlab.com/HankG/dart-result-monad

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
